name: transfermarkt-datasets
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - kaggle==1.5.12
  - boto3
  - inflection
  - pip==21.0.1
  - gh
  - scrapy=2.4.1
  - inflection
  - protego
  - python-dateutil
  - pytest
  - jupyter
  - streamlit
  - pip:
      - frictionless==4.1.0
      - pycountry==20.7.3
      - docker==5.0.0
      - dvc[s3]==2.1.0
