[tool.poetry]
name = "transfermarkt-datasets"
version = "0.1.0"
description = "Extract, prepare, publish and update Transfermarkt datasets."
authors = ["dcaribou <davidcereijo@live.com>"]

[tool.poetry.dependencies]
python = ">=3.8, <3.11, !=3.9.7"
frictionless = "4.40.8"
pandas = "^1.4.2"
boto3 = "^1.0.4"
inflection = "^0.5.1"
pytest = "^7.1.2"
dagster = "0.15.10"
dvc = {extras = ["s3"], version = "^2.17.0"}
scipy = "^1.8.0"
kaggle = "^1.5.12"
streamlit = "1.15.2"
geopy = "^2.2.0"
plotly = "^5.11.0"
transfermarkt-scraper = {git = "https://github.com/dcaribou/transfermarkt-scraper.git", branch = "main"}
dbt-duckdb = "^1.4.1"

[tool.poetry.group.dev.dependencies]
dagit = "0.15.10"
jupyter = "^1.0.0"
autopep8 = "^1.7.0"
shandy-sqlfmt = {extras = ["jinjafmt"], version = "^0.18.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
