assets:
  - name: players
    class: PlayersProcessor
    source: players.json # this is redundat, since the source is inferred from the runner name if not set
  - name: player_valuations
    class: PlayerValuationsProcessor
    source: players.json
  - name: games
    class: GamesProcessor
  - name: clubs
    class: ClubsProcessor
  - name: appearances
    class: AppearancesProcessor
  - name: competitions
    class: CompetitionsProcessor
settings:
  competition_codes: [
      'ES1', 'GB1', 'L1', 'IT1', 'FR1', 'GR1', 'PO1', 
      'BE1', 'UKR1', 'BE1', 'RU1', 'DK1', 'SC1', 'TR1',
      'NL1', 'NLP', 'NLSC', 'BESC', 'DFB', 'POSU', 'POCP',
      'CGB', 'UKRP', 'RUP', 'GBCS', 'SUC', 'DFL', 'CDR',
      'RUSS', 'GRP', 'SFA', 'CIT', 'DKP', 'FRCH', 'UKRS',
      'SCI', 'CL', 'EL', 'KLUB', 'ECLQ', 'CLQ', 'ELQ', 'USC'
    ]
