name: deploy-streamlit

on:
  workflow_run:
    workflows: [build]
    types: [completed]
    branches: [master]

jobs:
  deploy-streamlit:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY_PRIVATE }}

      - name: install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh

      - name: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLYCTL_INSTALL: /home/runner/.fly

        run: |
          export PATH="$FLYCTL_INSTALL/bin:$PATH"

          make streamlit_deploy PLATFORM=linux/amd64 TAG=master
