name: sync-streamlit

on:
  workflow_run:
    workflows: [build]
    types: [completed]
    branches: [master]

jobs:
  sync-streamlit:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh

      - uses: extractions/setup-just@v2

      - name: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLYCTL_INSTALL: /home/runner/.fly

        run: |
          export PATH="$FLYCTL_INSTALL/bin:$PATH"

          just --set platform "linux/amd64" --set tag master streamlit_deploy
